unique_ids:
  forms:
    MainForm: LTEZNWSXHMM4B6HJYOXUVYORKJD4LRUE
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: 4KXWZ7QMHFBVQEZGOJDATL7GKYUTQ2ZS
    theme.css: FHPR5QHNA5XRJYS2A73HMOWN3AE3OX2L
  scripts: {}
