unique_ids:
  forms:
    MainForm: LTEZNWSXHMM4B6HJYOXUVYORKJD4LRUE
  modules: {}
  server_modules:
    NatureGuides: '1719103861810429246762980.7155'
    NatureGuides.Guide: '1719103928564732949630995.1636'
  assets:
    standard-page.html: 4KXWZ7QMHFBVQEZGOJDATL7GKYUTQ2ZS
    theme.css: FHPR5QHNA5XRJYS2A73HMOWN3AE3OX2L
  scripts: {}
